name: PyLint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: Silleellie/pylint-github-action@v2.1
      with:
        lint-path: |
          Tools/Python
        python-version: 3.11
        requirements-path: yml/requirements.txt

